# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Requests

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  dependabot-automerge:
        name: Dependabot Auto Merge
        needs: build-and-test
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        runs-on: ubuntu-latest
        steps:
            - uses: fastify/github-action-merge-dependabot@v2.0.0
              with:
                  github-token: ${{secrets.github_token}}
                  merge-method: 'rebase'